export const APP_HTML = `<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>Campanhas privadas · Rotacionador</title>
  <style>
    :root{font-family:Inter,system-ui,sans-serif;color:#172033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0;padding:24px}main{max-width:1080px;margin:auto}.hidden{display:none!important}header{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:22px}.brand{display:flex;align-items:center;gap:12px}.logo{width:42px;height:42px;border-radius:11px;background:#3157d5;color:white;display:grid;place-items:center;font-weight:900}h1,h2,h3,p{margin-top:0}h1{font-size:24px;margin-bottom:3px}p,.muted{color:#65738a}.small{font-size:13px}.card,section{background:#fff;border:1px solid #e2e8f0;border-radius:14px;box-shadow:0 5px 20px #243b5a0b}.auth{max-width:430px;margin:8vh auto;padding:24px}.tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;background:#eef2f7;padding:5px;border-radius:10px;margin:20px 0}.tabs button.active{background:#fff;color:#172033;box-shadow:0 1px 5px #17203318}.field{display:flex;flex-direction:column;gap:6px;margin-bottom:13px}label{font-size:13px;font-weight:700;color:#55647a}input,select{font:inherit;border:1px solid #cfd8e5;border-radius:8px;padding:11px;background:white}button{border:0;border-radius:8px;padding:10px 14px;font:inherit;font-weight:700;cursor:pointer}.primary{color:#fff;background:#3157d5}.secondary{color:#2445a7;background:#e9efff}.full{width:100%}.status{min-height:20px;margin:9px 0 0;font-size:13px;color:#b42318}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{padding:19px}.links{display:grid;gap:8px}.link-row{display:grid;grid-template-columns:1fr 2fr auto;gap:8px}.remove{background:#ffeded;color:#a32828;padding:0 12px}.actions{display:flex;gap:8px;flex-wrap:wrap}.campaigns{margin-top:18px;overflow:hidden}.campaign{padding:18px;border-bottom:1px solid #edf0f4;display:flex;justify-content:space-between;gap:16px;align-items:center}.campaign:last-child{border-bottom:0}.campaign h3{margin-bottom:5px}.url{color:#3157d5;word-break:break-all;font-size:13px}.badge{display:inline-block;padding:4px 8px;border-radius:99px;background:#edf2ff;color:#3157d5;font-size:11px;font-weight:700}.empty{padding:24px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:16px}.metric{padding:17px}.metric strong{display:block;font-size:26px;margin-top:4px}.recent{width:100%;border-collapse:collapse}.recent th,.recent td{text-align:left;padding:11px 18px;border-bottom:1px solid #edf0f4;font-size:13px}.recent th{font-size:11px;color:#65738a;text-transform:uppercase}@media(max-width:720px){body{padding:14px}.grid{grid-template-columns:1fr}.summary{grid-template-columns:1fr}.link-row{grid-template-columns:1fr}.campaign{align-items:flex-start;flex-direction:column}header{align-items:flex-start}}
  </style>
</head>
<body>
<main>
  <section id="auth" class="auth">
    <div class="brand"><div class="logo">R</div><div><h1>Rotacionador</h1><p class="small">Acesso privado</p></div></div>
    <div class="tabs"><button id="login-tab" class="active" type="button">Entrar</button><button id="register-tab" type="button">Criar conta</button></div>
    <form id="auth-form">
      <div class="field"><label for="email">E-mail</label><input id="email" type="email" autocomplete="email" maxlength="254" required></div>
      <div class="field"><label for="password">Senha</label><input id="password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></div>
      <p id="password-help" class="muted small hidden">Use no mínimo 12 caracteres.</p>
      <button id="auth-submit" class="primary full" type="submit">Entrar</button>
      <p id="auth-status" class="status" role="alert"></p>
    </form>
  </section>

  <div id="app" class="hidden">
    <header><div class="brand"><div class="logo">R</div><div><h1>Campanhas privadas</h1><p id="account" class="small"></p></div></div><button id="logout" class="secondary" type="button">Sair</button></header>
    <div class="summary"><div class="card metric"><span class="muted small">Campanhas</span><strong id="metric-campaigns">0</strong></div><div class="card metric"><span class="muted small">Acessos</span><strong id="metric-accesses">0</strong></div><div class="card metric"><span class="muted small">Destinos</span><strong id="metric-destinations">0</strong></div></div>
    <div class="grid">
      <section class="panel"><h2>Nova campanha</h2><form id="campaign-form"><div class="field"><label for="name">Nome</label><input id="name" maxlength="100" placeholder="Ex.: Grupo VIP agosto" required></div><div class="field"><label for="mode">Distribuição</label><select id="mode"><option value="rotation">Rotação sequencial</option><option value="random">Aleatória</option></select></div><div class="field"><label>Links de destino</label><div id="links" class="links"></div></div><div class="actions"><button id="add-link" class="secondary" type="button">+ Adicionar link</button><button class="primary" type="submit">Criar campanha</button></div><p id="campaign-status" class="status" role="alert"></p></form></section>
      <section class="panel"><h2>Separado por pessoa</h2><p>Esta área usa um armazenamento exclusivo para sua conta. Outras pessoas não conseguem listar ou editar suas campanhas.</p><p class="muted small">Os links gerados continuam públicos para funcionar nos anúncios, mas o painel e os relatórios exigem seu login.</p></section>
    </div>
    <section class="campaigns"><div class="panel"><h2>Suas campanhas</h2></div><div id="campaigns"><p class="empty muted">Carregando…</p></div></section>
    <section class="campaigns"><div class="panel"><h2>Últimos acessos</h2></div><div style="overflow:auto"><table class="recent"><thead><tr><th>Campanha</th><th>Destino</th><th>Data e hora</th><th>Local</th></tr></thead><tbody id="recent"></tbody></table></div></section>
  </div>
</main>
<script type="module">
const $=selector=>document.querySelector(selector);let authMode='login';let report={campaigns:[],recent:[]};
function setMode(mode){authMode=mode;const register=mode==='register';$('#login-tab').classList.toggle('active',!register);$('#register-tab').classList.toggle('active',register);$('#auth-submit').textContent=register?'Criar conta':'Entrar';$('#password').autocomplete=register?'new-password':'current-password';$('#password-help').classList.toggle('hidden',!register);$('#auth-status').textContent=''}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})},cache:'no-store'});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||'Não foi possível concluir.');return data}
function showAuth(){authMode='login';setMode('login');$('#app').classList.add('hidden');$('#auth').classList.remove('hidden');$('#password').value=''}
function showApp(user){$('#account').textContent=user.email;$('#auth').classList.add('hidden');$('#app').classList.remove('hidden')}
function addLink(name='',url=''){const row=document.createElement('div');row.className='link-row';const nameInput=document.createElement('input');nameInput.className='link-name';nameInput.placeholder='Nome do grupo';nameInput.maxLength=80;nameInput.value=name;const urlInput=document.createElement('input');urlInput.className='link-url';urlInput.type='url';urlInput.placeholder='https://t.me/grupo';urlInput.maxLength=2048;urlInput.required=true;urlInput.value=url;const remove=document.createElement('button');remove.className='remove';remove.type='button';remove.textContent='Remover';remove.onclick=()=>row.remove();row.append(nameInput,urlInput,remove);$('#links').append(row)}
function formatDate(value){return value?new Date(value).toLocaleString('pt-BR'):'—'}
function render(){const total=report.campaigns.reduce((sum,item)=>sum+item.accesses,0);const destinations=report.campaigns.reduce((sum,item)=>sum+item.destinations.length,0);$('#metric-campaigns').textContent=String(report.campaigns.length);$('#metric-accesses').textContent=String(total);$('#metric-destinations').textContent=String(destinations);const container=$('#campaigns');container.replaceChildren();if(!report.campaigns.length){const empty=document.createElement('p');empty.className='empty muted';empty.textContent='Nenhuma campanha criada ainda.';container.append(empty)}else for(const campaign of report.campaigns){const row=document.createElement('div');row.className='campaign';const info=document.createElement('div');const heading=document.createElement('h3');heading.append(document.createTextNode(campaign.name+' '));const badge=document.createElement('span');badge.className='badge';badge.textContent=campaign.mode==='random'?'aleatória':'rotação';heading.append(badge);const link=document.createElement('div');link.className='url';link.textContent=location.origin+'/r/'+campaign.slug;const details=document.createElement('div');details.className='muted small';details.textContent=campaign.destinations.length+' destinos · '+campaign.accesses+' acessos · criado em '+formatDate(campaign.created_at);info.append(heading,link,details);const actions=document.createElement('div');actions.className='actions';const copy=document.createElement('button');copy.className='secondary';copy.type='button';copy.textContent='Copiar link';copy.onclick=async()=>{await navigator.clipboard.writeText(link.textContent);copy.textContent='Copiado';setTimeout(()=>copy.textContent='Copiar link',1200)};const open=document.createElement('a');open.className='secondary';open.href=link.textContent;open.target='_blank';open.rel='noreferrer';open.textContent='Abrir';open.style.textDecoration='none';actions.append(copy,open);row.append(info,actions);container.append(row)}const recent=$('#recent');recent.replaceChildren();if(!report.recent.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=4;cell.className='muted';cell.textContent='Nenhum acesso registrado.';row.append(cell);recent.append(row)}else for(const item of report.recent){const row=document.createElement('tr');for(const value of [item.campaign_name,item.destination_name||('Destino '+(item.group_index+1)),formatDate(item.accessed_at),[item.city,item.country].filter(Boolean).join(', ')||'—']){const cell=document.createElement('td');cell.textContent=value;row.append(cell)}recent.append(row)}}
async function load(){report=await api('/api/stats');render()}
$('#login-tab').onclick=()=>setMode('login');$('#register-tab').onclick=()=>setMode('register');
$('#auth-form').onsubmit=async event=>{event.preventDefault();const status=$('#auth-status');status.textContent='';try{const data=await api('/api/'+authMode,{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});showApp(data.user);await load()}catch(error){status.textContent=error.message}};
$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST',body:'{}'})}finally{showAuth()}};
$('#add-link').onclick=()=>addLink();
$('#campaign-form').onsubmit=async event=>{event.preventDefault();const status=$('#campaign-status');status.textContent='';const destinations=[...document.querySelectorAll('.link-row')].map(row=>({name:row.querySelector('.link-name').value,url:row.querySelector('.link-url').value}));try{await api('/api/campaigns',{method:'POST',body:JSON.stringify({name:$('#name').value,mode:$('#mode').value,destinations})});event.target.reset();$('#links').replaceChildren();addLink();addLink();await load()}catch(error){status.textContent=error.message}};
addLink();addLink();api('/api/me').then(async data=>{showApp(data.user);await load()}).catch(showAuth);
</script>
</body>
</html>`;
